- name: build web-portal to the portal server
  hosts: win
  become_method: runas
  roles:
  - { role: mysql_windows}
  - { role: apache_tomcat}
  - { role: wildfly_webserver}
  - { role: Deploy_tomcat}
